#ifndef DISTRHO_PLUGIN_INFO_H_INCLUDED
#include "../octaver/DistrhoPluginInfo.h"


#undef DISTRHO_PLUGIN_NAME
#undef DISTRHO_PLUGIN_URI
#define DISTRHO_PLUGIN_NAME  "AM/FM stereo chorus"
#define DISTRHO_PLUGIN_URI   "urn:jpc:amfm-stereo-chorus"

#undef DISTRHO_PLUGIN_NUM_INPUTS
#undef DISTRHO_PLUGIN_NUM_OUTPUTS
#define DISTRHO_PLUGIN_NUM_INPUTS    2
#define DISTRHO_PLUGIN_NUM_OUTPUTS   2

#endif // DISTRHO_PLUGIN_INFO_H_INCLUDED
