#ifndef DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DISTRHO_PLUGIN_INFO_H_INCLUDED

#define DISTRHO_PLUGIN_BRAND "JPC"
#define DISTRHO_PLUGIN_NAME  "AM/FM stereo mutator"
#define DISTRHO_PLUGIN_URI   "urn:jpc:amfm-stereo-mutator"

#define DISTRHO_PLUGIN_IS_RT_SAFE    1
#define DISTRHO_PLUGIN_NUM_INPUTS    4
#define DISTRHO_PLUGIN_NUM_OUTPUTS   2

#endif // DISTRHO_PLUGIN_INFO_H_INCLUDED
